insert into public.items (titel, kategorie, beschreibung, besitzer, ort, preis_pro_tag, verfuegbar, bild_url, created_at) values
  ('Abendkleid in Nachtblau, Größe 38', 'Mode', 'Bodenlang, einmal auf dem Uni-Ball getragen. Frisch gereinigt, mit passender Clutch.', 'Hannah', 'NDU, Foyer', 12, true, '/gegenstaende/abendkleid.jpg', now() - interval '1 hour'),
  ('Anzug mit Fliege, Größe 50', 'Mode', 'Dunkelgrau, schmal geschnitten. Für Bälle, Hochzeiten und Präsentationen, die Eindruck machen sollen.', 'Lukas', 'St. Pölten, Domplatz', 15, true, '/gegenstaende/anzug.jpg', now() - interval '2 hours'),
  ('Samtsessel in Senfgelb', 'Wohnen & Deko', 'Hingucker für Fotoshootings, Besichtigungen oder die WG-Party. Abholung mit Auto nötig.', 'Sofia', 'St. Pölten, Herzogenburger Straße', 8, true, '/gegenstaende/samtsessel.jpg', now() - interval '3 hours'),
  ('Vintage-Stehlampe aus Messing', 'Wohnen & Deko', 'Warmes Licht, 1,60 m hoch. Macht jede Ecke wohnlich – auch für eine Wohnungsbesichtigung.', 'Jonas', 'NDU, Werkstatt', 4, true, '/gegenstaende/stehlampe.jpg', now() - interval '4 hours'),
  ('Beamer mit Leinwand', 'Technik', 'Full HD, HDMI-Kabel liegt bei. Für Filmabende und Präsentationen. Bitte pfleglich behandeln.', 'Studienvertretung', 'NDU, Raum 2.04', 0, true, '/gegenstaende/beamer.jpg', now() - interval '5 hours'),
  ('Akkuschrauber mit Bit-Set', 'Technik', 'Zwei Akkus, Ladegerät und 30 Bits. Reicht für jedes WG-Regal und jeden Umzug.', 'Emil', 'St. Pölten, Wiener Straße', 3, true, '/gegenstaende/akkuschrauber.jpg', now() - interval '6 hours'),
  ('Campingzelt für drei', 'Freizeit', 'In zehn Minuten aufgebaut, wasserdicht getestet. Ideal fürs Festival oder ein Wochenende am See.', 'Mira', 'St. Pölten, Hauptbahnhof', 0, true, '/gegenstaende/campingzelt.jpg', now() - interval '7 hours'),
  ('Systemkamera mit zwei Objektiven', 'Technik', 'Dieser Gegenstand ist gerade verliehen und sollte in der Liste nicht auftauchen.', 'Ben', 'NDU, Foyer', 10, false, '/gegenstaende/systemkamera.jpg', now() - interval '8 hours');
